### ISSUE TITLE
Migrate from Gitlab-CI to GitHub flow

### ISSUE THREAD

**Issue by iRhonin** [SAY-DAO/meta#3]

**Comment by iRhonin** [comment]
@ehsan-g @Elhamne @babak-gholampour
I have moved [backend](https://github.com/SAY-DAO/backend) and [DApp](https://github.com/SAY-DAO/dapp-landing-page) repositories to GitHub entirely.

You should **remove** your local clones and clone it from Github to use the correct remote.

@ehsan-g Panel (old) and Webapp are still on the GitLab, we need to move those to our Github organization as a **public** repo to set up their CI/CD, I need your approval to do this.

**Comment by ehsan-g** [comment]
I will get back to you on this

**Comment by iRhonin** [comment]
Panel (old) and Webapp will be imported in the future to the SAY-DAO.
